import { Link } from "@/components/Link";

export const title = "Terms of Use · Broto";

export const description = "The rules of using Broto and the limits of what a photo analysis can tell you.";

export function Body() {
  return (
    <>
      <h1>Terms of Use</h1>
      <p className="updated">Effective 22 August 2026</p>

      <p className="intro">By creating a Broto account you agree to these terms. If you disagree with any part of them, do not use the app.</p>

      <h2>What Broto does</h2>
      <p>Broto is an app that helps you care for plants. You photograph a plant and get a suggested species, a differential diagnosis and a care plan. The app also has <strong>Brotinho</strong>, an assistant that answers plant care questions in writing.</p>

      <div className="callout warn">
        <p className="title">An automated suggestion, not a report</p>
        <p>The identification, the diagnosis and Brotinho's replies are generated by an artificial intelligence model. <strong>They can be wrong.</strong> They are a starting point for observing your plant, not a technical opinion.</p>
        <p>Broto is <strong>not</strong> a substitute for an agronomist, a botanist or a veterinarian.</p>
      </div>

      <div className="callout danger">
        <p className="title">Never use Broto to decide whether something is edible</p>
        <p>The app does not report edibility and must not be used for that purpose under any circumstances. Edible plants have toxic lookalikes, and a mistake here can be fatal.</p>
        <p>The pet toxicity warning is informational and based on the suggested species. If you suspect your pet has eaten a plant, go to a veterinarian immediately — do not consult the app.</p>
      </div>

      <h2>Pests and disease treatment</h2>
      <p>When the app suggests treatment, it prioritises cultural management — pruning the affected leaf, adjusting watering, improving airflow, isolating the plant. When it mentions a product, it names only the category. <strong>Broto never gives pesticide dosages.</strong> Always follow the manufacturer's label.</p>

      <h2>Your account</h2>
      <ul>
        <li>You must be 13 or older to create an account.</li>
        <li>The information you provide must be truthful.</li>
        <li>You are responsible for keeping your password safe.</li>
        <li>An account belongs to one person; do not share it.</li>
      </ul>

      <h2>Your photos</h2>
      <p>The photos you send remain yours. You grant us only the licence needed to store them in your account, send them to the vision model and display them back to you inside the app. We do not use your photos in marketing material and we do not make them public.</p>

      <h2>What is not allowed</h2>
      <ul>
        <li>Using the app for unlawful purposes, including identifying plants whose cultivation is prohibited.</li>
        <li>Circumventing analysis limits or the credit system.</li>
        <li>Reverse engineering, automating requests or overloading the service.</li>
        <li>Uploading images of third parties without permission, or offensive and illegal content.</li>
      </ul>
      <p>Accounts that break these rules may be suspended or terminated.</p>

      <h2>Subscription</h2>
      <p>Broto offers a three-day trial with full access from sign-up, paid one-off analyses and a complete subscription with up to 40 analyses and 150 Brotinho messages a month. The full conditions, including prices, cancellation and refunds, are in <Link href="/en/refund">Subscription and refunds</Link>.</p>

      <h3>Fair use limit</h3>
      <p>The <strong>40 analyses per month</strong> apply to the analyses included in your plan. <strong>One-off analyses you buy sit outside that limit</strong> — you can use them even when the month is full. On top of that, each account can run at most <strong>50 analyses per day</strong>, counting everything, and send at most <strong>150 messages per month</strong> to Brotinho, with a maximum of <strong>30 per day</strong>. No Broto plan is unlimited. The counter resets at midnight UTC. The daily ceiling exists to protect the service from automated use and shared accounts — normal use never comes close to it. Failed analyses do not count towards the limit.</p>

      <h3>Who sells the subscription</h3>
      <p>Subscriptions are sold by the <strong>App Store</strong> or <strong>Google Play</strong>, depending on where you downloaded the app. They charge you, issue the receipt and process refunds. These Terms govern the use of Broto; the purchase itself also follows the terms of the store where it was made.</p>

      <h2>Apple-required terms</h2>
      <p>If you use Broto on an Apple device, the following also apply, as required by the App Store:</p>
      <ul>
        <li>This agreement is between you and 61.021.870 Ghabriel Elias Fonseca de Souza, <strong>not with Apple</strong>. Apple is not responsible for the app or its content.</li>
        <li>The licence is personal, non-transferable and limited to Apple devices that you own or control, under the App Store Usage Rules.</li>
        <li>Support and maintenance of the app are our responsibility. Apple has no obligation to provide them.</li>
        <li>If the app fails to conform to any applicable warranty, you may notify Apple, which will refund the purchase price. To the maximum extent permitted by law, that is Apple's only warranty obligation.</li>
        <li>We are responsible for claims by you or third parties relating to the app, including product liability, regulatory compliance and intellectual property infringement claims.</li>
        <li>You represent that you are not located in a country subject to a U.S. Government embargo and are not on any prohibited party list.</li>
        <li>Apple and its subsidiaries are third-party beneficiaries of these Terms and may enforce them directly against you.</li>
      </ul>

      <h2>Availability</h2>
      <p>We work to keep the app running, but we do not guarantee uninterrupted service. We may change, suspend or discontinue features, giving reasonable notice when the change is significant.</p>

      <h2>Limitation of liability</h2>
      <p>To the extent permitted by Brazilian law, we are not liable for damages arising from decisions you make based on the app's suggestions, including the loss or death of plants. Nothing here removes the rights granted to you by the Brazilian Consumer Protection Code.</p>

      <h2>Governing law</h2>
      <p>These terms are governed by Brazilian law. The courts of your domicile are competent to resolve any dispute, as provided by the Brazilian Consumer Protection Code.</p>
    </>
  );
}
